# http service port for request health status
status_port = 11005
dest_folder = "/watchfolder"

# default is libx265
encode_type = "libx265"

# new file extension, default is mp4
new_file_type = "mkv"

[bus]
bus = "nsq"
in_topic = "ffmpeg"
in_channel = "ffmpeg"

nsqd_hosts = ["nsqd:4150"]
lookupd_hosts = ["nsqlookupd:4161"]

